# Generated by Django 2.2.14 on 2020-07-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='clase',
            new_name='clases',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombre',
            new_name='nombre_estudiante',
        ),
    ]
