# Generated by Django 2.2.14 on 2020-07-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20200719_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='clases',
        ),
    ]
