# Generated by Django 2.2.14 on 2020-07-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20200719_1854'),
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ManyToManyField(to='estudiante.estudiante'),
        ),
    ]
