# Generated by Django 2.2.14 on 2020-07-20 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_remove_estudiante_clases'),
        ('clase', '0002_clase_estudiantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='clase',
            name='estudiantes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
            preserve_default=False,
        ),
    ]
